move msgs to their own package, use ament auto
ApexAI/reference-system-autoware pull request #1
Opened 2021-08-30 21:09 UTC by flynneva

- creates separate reference_interfaces package for future message definition
- use ament_cmake_auto to reduce CMake code and reduce future maintenance
-  had to change the name of the message idl file to match the struct name, otherwise errors ensue due to missing auto-gen hpp file
- add header to msg idl file (was included but not used before)

2021-08-30 21:53 UTC, flynneva commented
@elfenpiff one thing I am unsure about is if we should even have the `Header` included in the message definition....since then the inclusion of the header changes the size of the message.

2021-08-31 08:24 UTC, elfenpiff commented
@flynneva I think we can remove the `Header` include from the message definition.

Is it good practice in ROS2 to separate the message definitions from the actual source code? I am not so familiar with the best practices in ROS2 and I was wondering why you separated them. If so then I have to consider when I am writing the next ROS2 package.

2021-08-31 08:28 UTC, elfenpiff requested changes

2021-08-31 08:28 UTC, elfenpiff commented on reference_interfaces/msg/Message1kb.idl
> +      std_msgs::msg::Header header;
I think we can remove this and the include.

2021-08-31 08:28 UTC, elfenpiff commented on reference_interfaces/msg/Message1kb.idl
> +      int64 data[1024];
This message has actually the size of 8kb and not 1kb. This array size has to adjusted to 128 to fit the name - whoopsie.

2021-08-31 16:32 UTC, flynneva commented
> Is it good practice in ROS2 to separate the message definitions from the actual source code?

in general, yes it is good practice. isolates the msgs to make them more easily reusable by other packages while also reducing code in the package that uses the msgs.  I cant find a specific "best practices" document that show this for ROS but you can see it in practice just by looking at how other packages are structured (see [ROS index `msgs` search](https://index.ros.org/search/?term=msgs) for a quick overview)

2021-09-01 12:53 UTC, merged